//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatioMetaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class question_data
    {
        public string id { get; set; }
        public string user_id { get; set; }
        public Nullable<bool> is_free { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string question { get; set; }
    }
}
