//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreatioUsersData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information
    {
        public string Id { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Email { get; set; }
        public string Ville { get; set; }
        public string CodePostal { get; set; }
        public string TelephoneDomicile { get; set; }
        public string TelephoneBureau { get; set; }
        public string TelephonePortable { get; set; }
        public string DateDeNaissance { get; set; }
    }
}
